services:
  - type: web
    name: discord-music-bot
    env: node
    plan: free
    buildCommand: |
      echo "=== Installing system dependencies ==="
      apt-get update && apt-get install -y python3 python3-pip
      echo "=== Installing yt-dlp ==="
      pip3 install yt-dlp
      echo "=== Verifying yt-dlp installation ==="
      yt-dlp --version
      which yt-dlp
      echo "=== Installing Node.js dependencies ==="
      npm ci --only=production --no-audit --no-fund
      echo "=== Build completed successfully ==="
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: NPM_CONFIG_PRODUCTION
        value: true
      - key: YTDL_NO_UPDATE
        value: true
    healthCheckPath: /
    autoDeploy: true
    runtime: node
    rootDir: .
    disk:
      name: bot-storage
      mountPath: /tmp
      sizeGB: 1
