services:
  - type: web
    name: discord-music-bot
    env: node
    plan: free
    buildCommand: npm ci && pip3 install yt-dlp
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
    runtime: node
    rootDir: .
    disk:
      name: bot-storage
      mountPath: /tmp
      sizeGB: 1
