services:
  - type: web
    name: discord-music-bot
    env: node
    plan: free
    buildCommand: |
      echo "=== Installing Node.js dependencies (including yt-dlp-exec) ==="
      npm ci --only=production --no-audit --no-fund
      echo "=== Build completed successfully ==="
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: NPM_CONFIG_PRODUCTION
        value: true
      - key: YTDL_NO_UPDATE
        value: true
    healthCheckPath: /
    autoDeploy: true
    runtime: node
    rootDir: .
    disk:
      name: bot-storage
      mountPath: /tmp
      sizeGB: 1
